PDFCMS/Controllers/SubscriberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PDFCMS.Models;
using System.IO;
using System.Text.RegularExpressions;
using PagedList;

namespace PDFCMS.Controllers
{
    [Authorize]
    public class SubscriberController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Subscriber/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "email_desc" : "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var subscribers = from s in db.Subscribers
                             select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                subscribers = subscribers.Where(s => s.Email.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "email_desc":
                    subscribers = subscribers.OrderByDescending(s => s.Email);
                    break;
                default:
                    subscribers = subscribers.OrderBy(s => s.Email);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(subscribers.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Subscriber/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscriber subscriber = db.Subscribers.Find(id);
            if (subscriber == null)
            {
                return HttpNotFound();
            }
            return View(subscriber);
        }

        // GET: /Subscriber/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Subscriber/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SubscriberId,Email")] Subscriber subscriber)
        {

            if (ModelState.IsValid)
            {
                if (db.Subscribers.Where(x => x.Email.Equals(subscriber.Email, StringComparison.InvariantCultureIgnoreCase)).Count() > 0)
                {
                    ViewData.ModelState.AddModelError("Email", "Email has already been subscribed.");
                }
                else
                {
                    db.Subscribers.Add(subscriber);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(subscriber);
        }

        // GET: /Subscriber/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscriber subscriber = db.Subscribers.Find(id);
            if (subscriber == null)
            {
                return HttpNotFound();
            }
            return View(subscriber);
        }

        // POST: /Subscriber/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SubscriberId,Email")] Subscriber subscriber)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subscriber).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(subscriber);
        }

        // GET: /Subscriber/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subscriber subscriber = db.Subscribers.Find(id);
            if (subscriber == null)
            {
                return HttpNotFound();
            }
            return View(subscriber);
        }

        // POST: /Subscriber/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public string DeleteConfirmed(int id)
        {
            string message = "Success";
            try
            {
                Subscriber sub= db.Subscribers.Find(id);
                db.Subscribers.Remove(sub);
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                message = "Failure";
            }
            return message;
            //return RedirectToAction("Index", new { fileId=fileId});
        }
        public ActionResult Import()
        {
            return View();
        }
        [HttpPost, ActionName("Import")]
        public ActionResult Import(Subscriber subscriber)
        {
            if (subscriber != null && subscriber.File == null)
            {
                ViewData.ModelState.AddModelError("File", "Please upload your file.");
            }
            else
            {
                // Set up DataTable place holder
                string fileName = Path.GetFileName(subscriber.File.FileName);
                string path = Path.Combine(Server.MapPath("~/App_Data/uploads/subscriber"), fileName);
                System.IO.FileInfo file = new System.IO.FileInfo(path);
                file.Directory.Create(); // If the directory already exists, this method does nothing.
                subscriber.File.SaveAs(path);
                var subscribers = new List<Subscriber>();
                if (subscriber.File != null && subscriber.File.ContentLength > 0)
                {
                    if (subscriber.File.FileName.EndsWith(".csv"))
                    {
                        using (var rd = new StreamReader(path))
                        {
                            while (!rd.EndOfStream)
                            {
                                var line = rd.ReadLine();
                                subscribers.Add(new Subscriber { Email = line });
                            }
                        }
                        if (subscribers.Count > 0)
                        {
                            using (var context = new ApplicationDbContext())
                            {
                                using (var dbContextTransaction = context.Database.BeginTransaction())
                                {
                                    try
                                    {   // some stuff in dbcontext
                                        //context.Database.ExecuteSqlCommand("TRUNCATE TABLE SUBSCRIBERS");
                                        int size = subscribers.Count;
                                        for (int i = 0; i < size; i++)
                                        {
                                            string emailtofind=subscribers[i].Email;
                                            List<Subscriber> storedSub = db.Subscribers.Where(x => x.Email == emailtofind).ToList();
                                            if (storedSub.Count() == 0)
                                            {
                                                context.Subscribers.Add(subscribers[i]);
                                            }
                                        }

                                        context.SaveChanges();
                                        dbContextTransaction.Commit();
                                        return RedirectToAction("Index");
                                    }
                                    catch (Exception ex)
                                    {
                                        dbContextTransaction.Rollback();
                                        throw;
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("File", "Only CSV file format is supported.");
                        return View();
                    }
                }
                else
                {
                    ModelState.AddModelError("File", "Please upload a CSV file.");
                }
            }
            return View(subscriber);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PDFCMS/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PDFCMS.Models;
using PagedList;
namespace PDFCMS.Controllers
{
    public class TOCController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /TOC/
        public ActionResult Index(int fileId, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.PageSortParm = String.IsNullOrEmpty(sortOrder) ? "page" : "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var Tocs = from s in db.Tocs
                        select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                Tocs = Tocs.Where(s => s.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "page":
                    Tocs = Tocs.OrderBy(s => s.PageNo);
                    break;
                default:
                    Tocs = Tocs.OrderBy(s => s.PageNo);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            List<TOC> tocList = Tocs.Where(t=>t.FileId==fileId).ToList();
            foreach (TOC toc in tocList)
            {
                if (toc.ParentId != null && toc.ParentId > 0)
                {
                    toc.Parent = db.Tocs.Find(toc.ParentId);
                }
            } 
            return View(tocList.ToList().ToPagedList(pageNumber, pageSize));
        }

        // GET: /TOC/Create
        public ActionResult Create(int fileId)
        {
            var model = new TOC
            {
                Topics = db.Tocs.Where(t=>t.FileId==fileId).ToList(),
                FileId=fileId,
                ParentId=0
            };
            return View(model);
        }

        // POST: /TOC/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TOC topic)
        {
            if (ModelState.IsValid)
            {
                CategoryFile editFile = db.Files.Find(topic.FileId);
                if (editFile != null)
                {
                    editFile.Toc_Version = editFile.Toc_Version + 1;
                    db.Entry(editFile).State = EntityState.Modified;
                    db.SaveChanges();
                }
                db.Tocs.Add(topic);
                db.SaveChanges();
                return RedirectToAction("Index", new { fileId = topic.FileId });
            }
            topic.Topics = db.Tocs.ToList();
            return View(topic);
        }

        // GET: /TOC/Edit/5
        public ActionResult Edit(int? id,int fileId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TOC topic = db.Tocs.Find(id);
            if (topic== null)
            {
                return HttpNotFound();
            }
            topic.Topics = db.Tocs.Where(t => t.TopicId != id && t.FileId == fileId).ToList();
            topic.FileId = fileId;
            
            return View(topic);
        }

        // POST: /TOC/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TOC topic)
        {
            if (ModelState.IsValid)
            {
                CategoryFile editFile = db.Files.Find(topic.FileId);
                if (editFile != null)
                {
                    editFile.Toc_Version = editFile.Toc_Version + 1;
                    db.Entry(editFile).State = EntityState.Modified;
                    db.SaveChanges();
                }
                db.Entry(topic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { fileId = topic.FileId });
            }
            topic.Topics = db.Tocs.Where(t => t.TopicId != topic.TopicId && t.FileId==topic.FileId).ToList();
            topic.FileId = topic.FileId;
            return View(topic);
        }

        // GET: /TOC/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TOC TOC = db.Tocs.Find(id);
            if (TOC == null)
            {
                return HttpNotFound();
            }
            return View(TOC);
        }

        // POST: /TOC/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public string DeleteConfirmed(int id)
        {
            string message="Success";
            try{
                TOC TOC = db.Tocs.Find(id);
                CategoryFile editFile = db.Files.Find(TOC.FileId);
                if (editFile != null)
                {
                    editFile.Toc_Version = editFile.Toc_Version + 1;
                    db.Entry(editFile).State = EntityState.Modified;
                    db.SaveChanges();
                }
                db.Tocs.Remove(TOC);
                db.SaveChanges();
            }
            catch(Exception ex){
                message="Failure";
            }
            return message;
            //return RedirectToAction("Index", new { fileId=fileId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PDFCMS/Views/TOC/Create.cshtml
@model PDFCMS.Models.TOC

@{
    ViewBag.Title = "Table of Content";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-md-7">
            <div class="page-breadcrumb-wrap">
                <div class="page-breadcrumb-info">
                    <h2 class="breadcrumb-titles">@ViewBag.Title</h2>
                    <ul class="list-page-breadcrumb">
                        <li>
                            @Html.ActionLink("Home", "Index", "Subscriber")
                        </li>
                        <li>
                            @Html.ActionLink("Files", "Index", "File")
                        </li>
                        <li>@ViewBag.Title</li>
                        <li class="active-page">Create</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-5">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="box-widget widget-module">
            <div class="widget-head clearfix">
                @*<span class="h-icon"><i class="fa fa-bars"></i></span>*@
                <h4>Topic Create</h4>
            </div>
            <div class="widget-container">
                <div class=" widget-block">

                    @using (Html.BeginForm("Create", "TOC", new { ReturnUrl = ViewBag.ReturnUrl, fileId = Request.Params["fileId"] }, FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => model.FileId)

                        <div class="form-group">
                            <label class="control-label col-md-2" for="title">Topic Name</label>
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Enter Topic Name" })
                                <label for="name" class="error"><span class="error-custom">@Html.ValidationMessageFor(model => model.Name)</span></label>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label class="control-label col-md-2" for="title">Page No.</label>
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.PageNo, new { @class = "form-control", @placeholder = "Enter Page Number", @type = "number", @min = "1" })
                                <label for="pageno" class="error"><span class="error-custom">@Html.ValidationMessageFor(model => model.PageNo)</span></label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="category">Parent Topic</label>
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.ParentId, Model.Topics.Select(c => new SelectListItem
                               {
                                   Text = c.Name,
                                   Value = c.TopicId.ToString()
                               }),"", new { @class = "form-control" })
                            </div>
                        </div>

                        @Html.ValidationSummary(true)
                        <div class="form-group">
                            <div class="col-md-offset-5">
                                <input type="submit" value="Create" class="btn btn-primary" />
                                @Html.ActionLink("Cancel", "Index", "TOC", new { fileId = @Request.Params["fileid"] }, new { @class = "btn btn-default" })
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section script
    {
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $("#files .anchor").addClass("active");
            $("#files ul").show();
        });
    </script>
}

PDFCMS/Views/TOC/Delete.cshtml
@model PDFCMS.Models.TOC

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Topic</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.page_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.page_no)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PDFCMS/Views/TOC/Details.cshtml
@model PDFCMS.Models.TOC

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Topic</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.page_no)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.page_no)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TopicId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PDFCMS/Views/TOC/Edit.cshtml
@model PDFCMS.Models.TOC

@{
    ViewBag.Title = "Table of Content";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-md-7">
            <div class="page-breadcrumb-wrap">
                <div class="page-breadcrumb-info">
                    <h2 class="breadcrumb-titles">@ViewBag.Title</h2>
                    <ul class="list-page-breadcrumb">
                        <li>
                            @Html.ActionLink("Home", "Index", "Subscriber")
                        </li>
                        <li>
                            @Html.ActionLink("Files", "Index", "File")
                        </li>
                        <li>@ViewBag.Title</li>
                        <li class="active-page">Edit</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-5">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="box-widget widget-module">
            <div class="widget-head clearfix">
                @*<span class="h-icon"><i class="fa fa-bars"></i></span>*@
                <h4>Topic Edit</h4>
            </div>
            <div class="widget-container">
                <div class=" widget-block">

                    @using (Html.BeginForm("Edit", "TOC", new { ReturnUrl = ViewBag.ReturnUrl, fileId = Request.Params["fileId"] }, FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.HiddenFor(model => @Request.Params["fileid"])
                        @Html.HiddenFor(model => model.TopicId)
                        <div class="form-group">
                            <label class="control-label col-md-2" for="title">Topic Name</label>
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @placeholder = "Enter Topic Name" })
                                <label for="name" class="error"><span class="error-custom">@Html.ValidationMessageFor(model => model.Name)</span></label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="title">Page No.</label>
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.PageNo, new { @class = "form-control", @placeholder = "Enter Page Number", @type = "number", @min = "1" })
                                <label for="pageno" class="error"><span class="error-custom">@Html.ValidationMessageFor(model => model.PageNo)</span></label>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-2" for="category">Parent Topic</label>
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.ParentId, Model.Topics.Select(c => new SelectListItem
                               {
                                   Text = c.Name,
                                   Value = c.TopicId.ToString()
                               }), "", new { @class = "form-control" })
                            </div>
                        </div>

                        @Html.ValidationSummary(true)
                        <div class="form-group">
                            <div class="col-md-offset-5">
                                <input type="submit" value="Save" class="btn btn-primary" />
                                @Html.ActionLink("Cancel", "Index", "TOC", new { fileId = @Request.Params["fileid"] }, new { @class = "btn btn-default" })
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section script
    {
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $("#files .anchor").addClass("active");
            $("#files ul").show();
        });
    </script>
}

PDFCMS/Views/TOC/Index.cshtml
@model PagedList.IPagedList<PDFCMS.Models.TOC>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Table of Content";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-md-7">
            <div class="page-breadcrumb-wrap">
                <div class="page-breadcrumb-info">
                    <h2 class="breadcrumb-titles">@ViewBag.Title</h2>
                    <ul class="list-page-breadcrumb">
                        <li>
                            @Html.ActionLink("Home", "Index", "Subscriber")
                        </li>
                        <li>
                            @Html.ActionLink("Files", "Index", "File")
                        </li>
                        <li class="active-page">@ViewBag.Title</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-5">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        @Html.ActionLink("Create New", "Create", "TOC", new { fileId = Request.Params["fileId"] }, new { @class = "btn btn-primary btn-block ex-noty" })
    </div>
</div>

<div class="table-responsive">
    <table class="table table-hover table-bordered matmix-dt bg-hc-border datatable">
        <thead>
            <tr>
                <th>
                    Topic Name
                </th>
                <th>
                    Page No.
                </th>
                <th>
                    Parent Topic
                </th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PageNo)
                    </td>

                    <td>
                        @if (item.ParentId != null && item.ParentId > 0)
                        { 
                            @Html.DisplayFor(modelItem => item.Parent.Name)
                        }
                    </td>
                    <td>
                        <div class="btn-toolbar" role="toolbar">
                            <div class="btn-group" role="group">
                                @Html.ActionLink("Edit", "Edit", new { id = item.TopicId, fileId = Request.Params["fileId"] }, new { @class = "btn btn-default btn-sm m-user-edit" })
                                <a class="btn btn-default btn-sm m-user-delete" onclick="javascript:removeTopic(@item.TopicId,@Request.Params["fileid"])">Delete</a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
            new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, fileId = @Request.Params["fileid"] }))
</div>

@section script
    {
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $("#files .anchor").addClass("active");
            $("#files ul").show();
        });
    </script>


    @Scripts.Render("~/Content/SiteAssets/js/jquery.dataTables.js")
    @Scripts.Render("~/Content/SiteAssets/js/dataTables.responsive.js")
    @Scripts.Render("~/Content/SiteAssets/js/dataTables.tableTools.js")
    @Scripts.Render("~/Content/SiteAssets/js/dataTables.bootstrap.js")
    @Scripts.Render("~/Content/SiteAssets/js/stacktable.js")
    <script type="text/javascript">


        function removeTopic(topicId, _fileId) {
            //var forgeryId = $("#forgeryToken").val();
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this Information!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete!",
                cancelButtonText: "No, cancel!",
                closeOnConfirm: false,
                closeOnCancel: true
            }, function (isConfirm) {
                if (isConfirm) {
                    jQuery.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete","TOC")',
                        ajaxasync: true,
                        data: { id: topicId},
                        //headers: {
                        //    'VerificationToken': forgeryId
                        //},
                        success: function (data) {
                            //alert(data);
                            //$(_this).parentsUntil('tbody').addClass("noty_animated bounceOutRight");
                            if (data == "Success") {
                                console.log('Removed');
                                //swal("Deleted!", "Information has been deleted.", "success");
                                swal({ title: "Deleted!", text: "Information has been deleted", timer: 2000, showConfirmButton: false });
                                var url = '@Url.Action("Index", "TOC")?fileId='+_fileId;
                                window.location.href = url;
                            }
                            else{
                                swal("Error!", "Something went wrong", "error");
                            }
                            
                        },
                        error: function (data) {
                            swal("Error!", "Something went wrong", "error");
                        }
                    });
                }
            });
        }

    </script>
}