PDFCMS/Controllers/GlossaryController.cs
using PDFCMS.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using System.Net;
using System.Data.Entity;
namespace PDFCMS.Controllers
{
    public class GlossaryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //
        // GET: /Glossary/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "alpha_desc" : "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var glossaries = from g in db.Glossary
                              select g;
            if (!String.IsNullOrEmpty(searchString))
            {
                glossaries = glossaries.Where(g => g.Word.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "alpha_desc":
                    glossaries = glossaries.OrderByDescending(g => g.Alphabet);
                    break;
                default:
                    glossaries = glossaries.OrderBy(g => g.Alphabet);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            //glossaries = glossaries.Where(t => t.FileId == fileId);
            return View(glossaries.ToPagedList(pageNumber, pageSize));
        }
        // GET: /Glossary/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Glossary/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)] 
        public ActionResult Create(Glossary glossary)
        {

            if (ModelState.IsValid)
            {
                db.Glossary.Add(glossary);
                db.SaveChanges();
                return RedirectToAction("Index");
                
            }

            return View(glossary);
        }

        // GET: /Glossary/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Glossary glossary = db.Glossary.Find(id);
            if (glossary == null)
            {
                return HttpNotFound();
            }
            return View(glossary);
        }

        // POST: /Glossary/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)] 
        public ActionResult Edit(Glossary glossary)
        {
            if (ModelState.IsValid)
            {
                db.Entry(glossary).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(glossary);
        }

        // GET: /Glossary/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Glossary glossary = db.Glossary.Find(id);
            if (glossary == null)
            {
                return HttpNotFound();
            }
            return View(glossary);
        }

        // POST: /Glossary/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public string DeleteConfirmed(int id)
        {
            string message = "Success";
            try
            {
                Glossary glossary = db.Glossary.Find(id);
                db.Glossary.Remove(glossary);
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                message = "Failure";
            }
            return message;
            //return RedirectToAction("Index", new { fileId=fileId});
        }

        public ActionResult Import()
        {
            return View();
        }
        [HttpPost, ActionName("Import")]
        public ActionResult Import(Glossary glossary)
        {
            if (glossary != null && glossary.File == null)
            {
                ViewData.ModelState.AddModelError("File", "Please upload your file.");
            }
            else
            {
                // Set up DataTable place holder
                string fileName = Path.GetFileName(glossary.File.FileName);
                string path = Path.Combine(Server.MapPath("~/App_Data/uploads/glossary"), fileName);
                System.IO.FileInfo file = new System.IO.FileInfo(path);
                file.Directory.Create(); // If the directory already exists, this method does nothing.
                glossary.File.SaveAs(path);
                var glossaries = new List<Glossary>();
                if (glossary.File != null && glossary.File.ContentLength > 0)
                {
                    if (glossary.File.FileName.EndsWith(".csv"))
                    {
                        using (var rd = new StreamReader(path))
                        {
                            while (!rd.EndOfStream)
                            {
                                var line = rd.ReadLine();
                                string[] parts = line.Split('|');
                                for (int i = 0; i < parts.Length; i++)
                                {
                                    parts[i] = parts[i].Trim();
                                }
                                if (parts.Length == 3)
                                {
                                    //glossaries.Add(new Glossary { Alphabet = parts[0], Word = parts[1], Definition = parts[2],FileId=fileId });
                                    glossaries.Add(new Glossary { Alphabet = parts[0], Word = parts[1], Definition = parts[2] });
                                }
                                else
                                {
                                    ModelState.AddModelError("File", "CSV file format is incorrect.");
                                    return View(glossary);
                                }
                            }
                        }
                        if (glossaries.Count > 0)
                        {
                            using (var context = new ApplicationDbContext())
                            {
                                using (var dbContextTransaction = context.Database.BeginTransaction())
                                {
                                    try
                                    {   // some stuff in dbcontext
                                        //string query = String.Format("DELETE FROM GLOSSARIES WHERE FILEID={0}",fileId);
                                        context.Database.ExecuteSqlCommand("TRUNCATE TABLE GLOSSARIES");
                                        //context.Database.ExecuteSqlCommand(query);
                                        int size = glossaries.Count;
                                        for (int i = 0; i < size; i++)
                                        {
                                            context.Glossary.Add(glossaries[i]);
                                        }

                                        context.SaveChanges();
                                        dbContextTransaction.Commit();
                                        //return RedirectToAction("Index", new { fileId = fileId });
                                        return RedirectToAction("Index");
                                    }
                                    catch (Exception ex)
                                    {
                                        dbContextTransaction.Rollback();
                                        throw;
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("File", "Only CSV file format is supported.");
                        return View(glossary);
                    }
                }
                else
                {
                    ModelState.AddModelError("File", "Please upload a CSV file.");
                }
            }
            return View(glossary);
        }
	}
}

PDFCMS/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PDFCMS.Models;
using PagedList;
namespace PDFCMS.Controllers
{
    public class TOCController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /TOC/
        public ActionResult Index(int fileId, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.PageSortParm = String.IsNullOrEmpty(sortOrder) ? "page" : "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var Tocs = from s in db.Tocs
                        select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                Tocs = Tocs.Where(s => s.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "page":
                    Tocs = Tocs.OrderBy(s => s.PageNo);
                    break;
                default:
                    Tocs = Tocs.OrderBy(s => s.PageNo);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            List<TOC> tocList = Tocs.Where(t=>t.FileId==fileId).ToList();
            foreach (TOC toc in tocList)
            {
                if (toc.ParentId != null && toc.ParentId > 0)
                {
                    toc.Parent = db.Tocs.Find(toc.ParentId);
                }
            } 
            return View(tocList.ToList().ToPagedList(pageNumber, pageSize));
        }

        // GET: /TOC/Create
        public ActionResult Create(int fileId)
        {
            var model = new TOC
            {
                Topics = db.Tocs.Where(t=>t.FileId==fileId).ToList(),
                FileId=fileId,
                ParentId=0
            };
            return View(model);
        }

        // POST: /TOC/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TOC topic)
        {
            if (ModelState.IsValid)
            {
                CategoryFile editFile = db.Files.Find(topic.FileId);
                if (editFile != null)
                {
                    editFile.Toc_Version = editFile.Toc_Version + 1;
                    db.Entry(editFile).State = EntityState.Modified;
                    db.SaveChanges();
                }
                db.Tocs.Add(topic);
                db.SaveChanges();
                return RedirectToAction("Index", new { fileId = topic.FileId });
            }
            topic.Topics = db.Tocs.ToList();
            return View(topic);
        }

        // GET: /TOC/Edit/5
        public ActionResult Edit(int? id,int fileId)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TOC topic = db.Tocs.Find(id);
            if (topic== null)
            {
                return HttpNotFound();
            }
            topic.Topics = db.Tocs.Where(t => t.TopicId != id && t.FileId == fileId).ToList();
            topic.FileId = fileId;
            
            return View(topic);
        }

        // POST: /TOC/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TOC topic)
        {
            if (ModelState.IsValid)
            {
                CategoryFile editFile = db.Files.Find(topic.FileId);
                if (editFile != null)
                {
                    editFile.Toc_Version = editFile.Toc_Version + 1;
                    db.Entry(editFile).State = EntityState.Modified;
                    db.SaveChanges();
                }
                db.Entry(topic).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { fileId = topic.FileId });
            }
            topic.Topics = db.Tocs.Where(t => t.TopicId != topic.TopicId && t.FileId==topic.FileId).ToList();
            topic.FileId = topic.FileId;
            return View(topic);
        }

        // GET: /TOC/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TOC TOC = db.Tocs.Find(id);
            if (TOC == null)
            {
                return HttpNotFound();
            }
            return View(TOC);
        }

        // POST: /TOC/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public string DeleteConfirmed(int id)
        {
            string message="Success";
            try{
                TOC TOC = db.Tocs.Find(id);
                CategoryFile editFile = db.Files.Find(TOC.FileId);
                if (editFile != null)
                {
                    editFile.Toc_Version = editFile.Toc_Version + 1;
                    db.Entry(editFile).State = EntityState.Modified;
                    db.SaveChanges();
                }
                db.Tocs.Remove(TOC);
                db.SaveChanges();
            }
            catch(Exception ex){
                message="Failure";
            }
            return message;
            //return RedirectToAction("Index", new { fileId=fileId});
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PDFCMS/Views/File/Create.cshtml
@model PDFCMS.Models.CategoryFile

@{
    ViewBag.Title = "Files";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-md-7">
            <div class="page-breadcrumb-wrap">
                <div class="page-breadcrumb-info">
                    <h2 class="breadcrumb-titles">Create</h2>
                    <ul class="list-page-breadcrumb">
                        <li>
                            @Html.ActionLink("Home", "Index", "Subscriber")
                        </li>
                        <li>
                            @Html.ActionLink("Files", "Index", "File")
                        </li>
                        <li class="active-page">Create</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-5">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="box-widget widget-module">
            <div class="widget-head clearfix">
                @*<span class="h-icon"><i class="fa fa-bars"></i></span>*@
                <h4>File Upload</h4>
            </div>
            <div class="widget-container">
                <div class=" widget-block">

                    @using (Html.BeginForm("Create", "File", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()
                            

                            <div class="form-group">
                                <label class="control-label col-md-2" for="categoryFile">File</label>
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.File, new { type = "file", @class = "form-control", @name = "categoryFile", @accept = "application/pdf" })
                                    <label for="categoryFile" class="error"><span class="error-custom">@Html.ValidationMessageFor(model => model.File)</span></label>
                                </div>
                            </div>
                        
                        <div class="form-group">
                                <label class="control-label col-md-2" for="title">Title</label>
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @placeholder = "Enter Title" })
                                    <label for="title" class="error"><span class="error-custom">@Html.ValidationMessageFor(model => model.Title)</span></label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-2" for="category">Category</label>
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.CategoryId, Model.Categories.Select(c => new SelectListItem
                               {
                                   Text = c.Name,
                                   Value = c.CategoryId.ToString()
                               }), new { @class = "form-control" })
                                </div>
                            </div>
                        
                        <div class="form-group">
                            @Html.LabelFor(model => model.pagesLimit, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(model => model.pagesLimit, new { @class = "form-control", @placeholder = "Enter Pages Limit", @type = "number" })
                                <label for="pagesLimit" class="error"><span class="error-custom">@Html.ValidationMessageFor(model => model.pagesLimit)</span></label>
                            </div>
                        </div>

                            @Html.ValidationSummary(true)
                            <div class="form-group">
                                <div class="col-md-offset-5">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                    @Html.ActionLink("Cancel", "Index", "File", null, new { @class = "btn btn-default" })
                                </div>
                            </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section script
    {
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $("#files .anchor").addClass("active");
            $("#files ul").show();
        });
    </script>
}

PDFCMS/Views/File/Delete.cshtml
@model PDFCMS.Models.File

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>File</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Version)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Version)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PDFCMS/Views/File/Details.cshtml
@model PDFCMS.Models.File

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>File</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Path)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Path)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Version)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Version)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.FileId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PDFCMS/Views/File/Index.cshtml
@model PagedList.IPagedList<PDFCMS.Models.CategoryFile>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Files";
}

<div class="page-breadcrumb">
    <div class="row">
        <div class="col-md-7">
            <div class="page-breadcrumb-wrap">
                <div class="page-breadcrumb-info">
                    <h2 class="breadcrumb-titles">View</h2>
                    <ul class="list-page-breadcrumb">
                        <li>
                            @Html.ActionLink("Home", "Index", "Subscriber")
                        </li>
                        <li class="active-page">Files</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-5">
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary btn-block ex-noty" })
    </div>
</div>

<div class="table-responsive">
    <table class="table table-hover table-bordered matmix-dt bg-hc-border datatable">
        <thead>
            <tr>
                <th>
                    Title
                </th>
                <th>
                    Category
                </th>
                <th>
                    Version
                </th>
                <th>
                    File
                </th>
                <th>Table of Content</th>
                <th>TOC Version</th>
                @*<th>Glossary</th>*@
                <th>Email Pages Limit</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
        @Html.DisplayFor(modelItem => item.Title)
    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>
                    
                    <td>
                        @Html.DisplayFor(modelItem => item.Version)
                    </td>
                    <td>
                        @Html.ActionLink(item.Name, "DownloadFile", new { fileName = item.Name })
                    </td>
                    <td>
                        <div class="btn-toolbar" role="toolbar">
                            <div class="btn-group" role="group">
                                @Html.ActionLink("View", "Index", "TOC", new { fileId = item.FileId }, new { @class = "btn btn-default btn-sm m-user-edit" })
                            </div>
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Toc_Version)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.pagesLimit)
                    </td>
                    @*<td>
                        <div class="btn-toolbar" role="toolbar">
                            <div class="btn-group" role="group">
                                @Html.ActionLink("View", "Index", "Glossary", new { fileId = item.FileId }, new { @class = "btn btn-default btn-sm m-user-edit" })
                            </div>
                        </div>
                    </td>*@
                    <td>
                        <div class="btn-toolbar" role="toolbar">
                            <div class="btn-group" role="group">
                                @Html.ActionLink("Edit", "Edit", new { id = item.FileId }, new { @class = "btn btn-default btn-sm m-user-edit" })
                                <a class="btn btn-default btn-sm m-user-delete" onclick="javascript:removeFile(@item.FileId)">Delete</a>
                            </div>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
</div>

@section script
    {
    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $("#files .anchor").addClass("active");
            $("#files ul").show();
        });
    </script>


    @Scripts.Render("~/Content/SiteAssets/js/jquery.dataTables.js")
    @Scripts.Render("~/Content/SiteAssets/js/dataTables.responsive.js")
    @Scripts.Render("~/Content/SiteAssets/js/dataTables.tableTools.js")
    @Scripts.Render("~/Content/SiteAssets/js/dataTables.bootstrap.js")
    @Scripts.Render("~/Content/SiteAssets/js/stacktable.js")
    <script type="text/javascript">


        function removeFile(fileId) {
            //var forgeryId = $("#forgeryToken").val();
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this Information!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete!",
                cancelButtonText: "No, cancel!",
                closeOnConfirm: false,
                closeOnCancel: true
            }, function (isConfirm) {
                if (isConfirm) {
                    jQuery.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete", "File")',
                        ajaxasync: true,
                        data: { id: fileId },
                        //headers: {
                        //    'VerificationToken': forgeryId
                        //},
                        success: function (data) {
                            //alert(data);
                            //$(_this).parentsUntil('tbody').addClass("noty_animated bounceOutRight");
                            if (data == "Success") {
                                console.log('Removed');
                                //swal("Deleted!", "Information has been deleted.", "success");
                                swal({ title: "Deleted!", text: "Information has been deleted", timer: 2000, showConfirmButton: false });
                                var url = '@Url.Action("Index", "File")';
                                window.location.href = url;
                            }
                            else{
                                swal("Error!", "Something went wrong", "error");
                            }

                        },
                        error: function (data) {
                            swal("Error!", "Something went wrong", "error");
                        }
                    });
                }
            });
        }

    </script>
}